version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  projects:
    build: ./services/projects
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/projects
    depends_on:
      - mongo

  gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - projects

volumes:
  mongo_data:
